services:
  mediamtx:
    image: bluenviron/mediamtx:1.19.2
    restart: unless-stopped
    environment:
      MTX_WEBRTCADDITIONALHOSTS: ${MEDIA_SERVER_IP}
    ports:
      - "8554:8554/tcp"
      - "8888:8888/tcp"
      - "8889:8889/tcp"
      - "8189:8189/udp"
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:ro
